import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateGamePDF = (gdd) => {

const doc = new jsPDF("p","mm","a4");

const pageWidth = doc.internal.pageSize.getWidth();

const center = pageWidth/2;

// ---------- COVER ----------

doc.setFillColor(10,12,30);
doc.rect(0,0,210,297,"F");

doc.setTextColor(255,255,255);

doc.setFont("helvetica","bold");

doc.setFontSize(30);

doc.text("GAME DESIGN",center,55,{align:"center"});

doc.text("DOCUMENT",center,70,{align:"center"});

doc.setFontSize(16);

doc.setTextColor(180,180,255);

doc.text("Generated by GameForge AI",center,90,{align:"center"});

doc.setDrawColor(140,90,255);

doc.line(45,105,165,105);

doc.setFontSize(26);

doc.setTextColor(255,255,255);

doc.text(gdd.document.title,center,130,{align:"center"});

doc.setFontSize(16);

doc.setTextColor(200,200,200);

doc.text(gdd.document.genre,center,145,{align:"center"});

doc.setFontSize(14);

doc.text(

new Date().toLocaleDateString(),

center,

165,

{align:"center"}

);

doc.addPage();

// ---------- GAME OVERVIEW ----------

doc.setFontSize(24);

doc.setTextColor(80,40,180);

doc.text("Game Overview",15,20);

autoTable(doc,{

startY:30,

theme:"grid",

head:[["Field","Value"]],

body:[

["Genre",gdd.document.genre],

["Platform",gdd.document.platform],

["Theme",gdd.document.theme],

["Audience",gdd.document.target_audience],

["Core Concept",gdd.game_overview.core_concept],

["Main Objective",gdd.game_overview.main_objective]

]

});

doc.addPage();

// ---------- STORY ----------

doc.setFontSize(24);

doc.text("Story",15,20);

autoTable(doc,{

startY:30,

theme:"striped",

head:[["Section","Content"]],

body:[

["Beginning",gdd.story_summary.introduction],

["Conflict",gdd.story_summary.main_conflict],

["Journey",gdd.story_summary.progression],

["Ending",gdd.story_summary.ending]

]

});
// ---------- CHARACTERS ----------

doc.addPage();

doc.setFontSize(24);
doc.setTextColor(80,40,180);
doc.text("Characters",15,20);

const characterRows=[];

gdd.characters_summary.forEach(character=>{

characterRows.push([
character.name,
character.role,
character.description
]);

});

autoTable(doc,{
startY:30,
theme:"grid",
head:[["Name","Role","Description"]],
body:characterRows
});

// ---------- LEVELS ----------

doc.addPage();

doc.setFontSize(24);
doc.text("Levels",15,20);

const levelRows=[];

gdd.levels_summary.forEach(level=>{

levelRows.push([
level.level,
level.name,
level.location,
level.objective
]);

});

autoTable(doc,{
startY:30,
theme:"grid",
head:[["Level","Name","Location","Objective"]],
body:levelRows
});

// ---------- GAMEPLAY ----------

doc.addPage();

doc.setFontSize(24);
doc.text("Gameplay",15,20);

autoTable(doc,{
startY:30,
theme:"grid",
head:[["Section","Information"]],
body:[

["Gameplay Style",gdd.gameplay_summary.gameplay_style],

["Progression",gdd.gameplay_summary.progression_system],

["Mechanics",
gdd.gameplay_summary.main_mechanics.join(", ")
],

["Rewards",
gdd.gameplay_summary.reward_system
]

]
});
// ---------- VISUAL STYLE ----------

doc.addPage();

doc.setFontSize(24);
doc.setTextColor(80,40,180);
doc.text("Visual Style",15,20);

autoTable(doc,{
startY:30,
theme:"grid",
head:[["Category","Details"]],
body:[

["Art Style",gdd.visual_summary.art_style],

["Visual Identity",gdd.visual_summary.visual_identity],

["Camera Style",gdd.visual_summary.camera_style],

["UI Style",gdd.visual_summary.ui_style],

["Color Palette",
gdd.visual_summary.color_palette.join(", ")
]

]
});

// ---------- DEVELOPMENT SUMMARY ----------

doc.addPage();

doc.setFontSize(24);
doc.text("Development Summary",15,20);

autoTable(doc,{
startY:30,
theme:"grid",
head:[["Category","Information"]],
body:[

[
"Estimated Scope",
gdd.development_notes.estimated_scope
],

[
"Project Complexity",
gdd.development_notes.project_complexity
],

[
"Strong Features",
gdd.development_notes.strongest_features.join("\n\n")
]

]
});

// ---------- THANK YOU PAGE ----------

doc.addPage();

doc.setFillColor(10,12,30);
doc.rect(0,0,210,297,"F");

doc.setTextColor(255,255,255);

doc.setFont("helvetica","bold");
doc.setFontSize(30);

doc.text(
"THANK YOU",
center,
70,
{
align:"center"
}
);

doc.setFontSize(18);

doc.setTextColor(180,180,255);

doc.text(
"For using GameForge AI",
center,
95,
{
align:"center"
}
);

doc.setDrawColor(130,90,255);
doc.line(45,115,165,115);

doc.setFontSize(22);

doc.setTextColor(255,255,255);

doc.text(
gdd.document.title,
center,
145,
{
align:"center"
}
);

doc.setFontSize(14);

doc.setTextColor(180,180,180);

doc.text(
"Generated completely by AI Agents",
center,
165,
{
align:"center"
}
);

doc.setFontSize(12);

doc.text(
"© GameForge AI",
center,
250,
{
align:"center"
}
);
// ---------- SAVE PDF ----------

const fileName =
`${gdd.document.title.replace(/\s+/g,"_")}_Game_Design_Document.pdf`;

doc.save(fileName);

};